version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  quota-approval-service:
    build: .
    environment:
      PORT: 8000
      QUOTA_SERVICE_URL: 'http://localhost:8080'
      ADMINS_ID_LIST: '[1,2,3,4,5,6,7]'
    ports:
      - 8000:8000